site_name: Grupo 09 


theme:
  name: material
  language: pt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
  toggle:
    icon: material/weather-night
    name: Alternar modo claro/escuro


nav:
  - Home : index.md
  - Atas:
      - 28/03/2025: atas/ata_28_03.md
      - 04/04/2025: atas/ata_04_04.md
  - Planejamento:
      - Ferramentas: planejamento/ferramentas.md 
  - Pr√©-rastreabilidade:
      - Rich Picture: pre-rastreabilidade/rich_picture.md
